# Generated by Django 3.2.23 on 2024-02-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapbook_code', models.CharField(max_length=6)),
                ('scrapbook_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('image', models.ImageField(default='images_in_static/exponential.png', upload_to='images_in_static')),
                ('scrapbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbooks.scrapbook')),
            ],
        ),
    ]
