# Generated by Django 3.2.23 on 2024-03-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbooks', '0002_alter_media_scrapbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='scrapbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrapbooks.scrapbook'),
        ),
    ]
