# Generated by Django 3.2.23 on 2024-03-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbooks', '0004_alter_media_scrapbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='scrapbook_theme',
            field=models.CharField(choices=[('template1', 'template 1 name'), ('template2', 'template 2 name')], default='template1', max_length=100),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('scrapbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbooks.scrapbook')),
            ],
        ),
    ]
