# Generated by Django 3.2.23 on 2024-04-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbooks', '0005_auto_20240319_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='images/exponential.png', upload_to='scrapbooks/static/images'),
        ),
    ]
