# Generated by Django 3.2.23 on 2024-04-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbooks', '0007_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='images/exponential.png', upload_to='images'),
        ),
    ]
