# Generated by Django 3.2.23 on 2024-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbooks', '0009_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='scrapbook_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='scrapbook_theme',
            field=models.CharField(choices=[('template1', 'Blue Flowers'), ('template2', 'Pink Stars')], default='template1', max_length=100),
        ),
    ]
