# Generated by Django 3.2.23 on 2024-04-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbooks', '0010_auto_20240416_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
